import Banner from "@/components/pages/landing/Banner";
import ServicesSection from "@/components/pages/landing/ServicesSection";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Perscripto | Home Page",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <section className="">
      <Banner/>

      <ServicesSection/>
    </section>
  );
}
